---
- name: Restart transparent RubyGems cache frontend
  community.docker.docker_compose_v2:
    project_src: "{{ devastation_paths.compose }}"
    services:
      - gem-cache-transparent
    state: restarted
