---
- name: Create MinIO storage data directory
  ansible.builtin.file:
    path: "{{ devastation_paths.storage }}/data"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Start storage MinIO service
  community.docker.docker_compose_v2:
    project_src: "{{ devastation_paths.compose }}"
    services:
      - storage
    state: present
